<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>LiveQuiz Cheater</title>
    <link rel="manifest" href="./manifest.json">
    <meta name="format-detection" content="telephone=no" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="theme-color" content="white"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <style type="text/css">
        body {
            margin: 0;
            background: #313252;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
        h1 {
            margin: 0;
            margin-bottom: 15px;
            font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-style: normal;
            font-weight: 600;
            font-size: 22px;
            line-height: 1.2;
        }
        .page {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            justify-content: center;
            min-width: 100vw;
            min-height: 100vh;
        }
        .content {
            padding: 15px;
            font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-style: normal;
            font-weight: 400;
            font-size: 15px;
            color: #ffffff;
            line-height: 1.4;
            text-align: center;
        }
    </style>
</head>
<body class="fullscreen">
<div class="page">

    <div id="content" class="content">
        <h1 id="title"><?= $answer ?></h1>
    </div>

</div>
<script>
    document.addEventListener("DOMContentLoaded", async () => {
        await navigator.serviceWorker.register("./ServiceWorker.js");
    });
</script>
</body>
</html>